import Link from 'next/link';
import { NavBrand } from '@/components/nav-brand';
import { SiteFooter } from '@/components/site-footer';

export const metadata = {
  title: 'Terms of Use — BioJalisco',
  description: 'Terms of use for the BioJalisco Species Identifier platform.',
};

export default function TermsPage() {
  return (
    <>
      <nav className="nav-bar nav-bar-wide">
        <NavBrand />
        <div className="nav-links">
          <Link href="/faq" className="nav-link">FAQ</Link>
        </div>
      </nav>

      <div className="legal-page">
        <div className="legal-content">
          <h1>Terms of Use</h1>
          <p className="legal-effective">Effective: March 8, 2026</p>

          <p>
            These terms govern your use of BioJalisco Species Identifier (&ldquo;the Platform&rdquo;),
            operated by CushLabs AI Services (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By using the Platform,
            you agree to these terms.
          </p>

          <h2>1. Platform Purpose</h2>
          <p>
            BioJalisco is a field research tool that assists with species identification using AI
            and scientific biodiversity databases. It is designed for conservation biologists, researchers,
            and authorized users conducting biodiversity surveys in Mexico.
          </p>

          <h2>2. Access</h2>
          <p>
            The Platform is currently invite-only. Access is granted through authenticated accounts
            managed via Clerk. You are responsible for maintaining the security of your account
            credentials. Unauthorized sharing of access is prohibited.
          </p>

          <h2>3. Acceptable Use</h2>
          <p>You agree to use the Platform only for lawful purposes related to biodiversity research,
            species identification, and conservation work. You will not:</p>
          <ul>
            <li>Attempt to reverse-engineer, scrape, or overload the Platform or its APIs</li>
            <li>Upload content that is illegal, harmful, or unrelated to species identification</li>
            <li>Share access credentials with unauthorized individuals</li>
            <li>Use the Platform to facilitate harm to wildlife or ecosystems</li>
          </ul>

          <h2>4. AI-Generated Content</h2>
          <p>
            Species identifications are generated by AI (GPT-4o Vision) and enriched with data from
            GBIF, iNaturalist, and EncicloVida (CONABIO). While we verify data against authoritative
            databases where possible, <strong>AI identifications are probabilistic and should not be
            treated as definitive taxonomic determinations</strong>. Always confirm identifications
            through expert review for research-critical decisions.
          </p>

          <h2>5. Data and Observations</h2>
          <p>
            Observations you create (photos, GPS coordinates, identification results) are stored
            securely and associated with your account. You retain ownership of your observation data.
            We may use anonymized, aggregated observation data for platform improvement and research
            purposes.
          </p>

          <h2>6. Third-Party Services</h2>
          <p>
            The Platform integrates with external services including OpenAI, GBIF, iNaturalist, and
            EncicloVida. These services have their own terms and data policies. We are not responsible
            for the availability or accuracy of third-party data.
          </p>

          <h2>7. No Warranty</h2>
          <p>
            The Platform is provided &ldquo;as is&rdquo; without warranties of any kind, express or
            implied. We do not guarantee the accuracy, completeness, or reliability of species
            identifications or biodiversity data. Use of the Platform for critical conservation
            decisions should be supplemented with expert verification.
          </p>

          <h2>8. Limitation of Liability</h2>
          <p>
            CushLabs AI Services shall not be liable for any direct, indirect, incidental, or
            consequential damages arising from your use of the Platform, including but not limited to
            incorrect identifications, data loss, or service interruptions.
          </p>

          <h2>9. Changes to Terms</h2>
          <p>
            We may update these terms at any time. Continued use of the Platform after changes
            constitutes acceptance of the updated terms. Material changes will be communicated to
            registered users.
          </p>

          <h2>10. Contact</h2>
          <p>
            For questions about these terms, contact us at{' '}
            <a href="mailto:info@cushlabs.ai" className="gbif-link">info@cushlabs.ai</a>.
          </p>
        </div>
      </div>

      <SiteFooter />
    </>
  );
}
